# Generated by Django 2.0.6 on 2018-06-18 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest_book',
            name='src_user_profile_img',
        ),
    ]
