# Generated by Django 2.0.6 on 2018-06-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_guest_book_src_user_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest_book',
            name='src_user_profile_img',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
